# To fetch schema from
introspection: file://IntrospectionQuery.txt

servers:
  - url: file://IntrospectionQuery.txt
    description: Test Server

info:
  description: |
    Docs for uois
  version: 1.0.0
  title: Docs

domains:
  - name: Fetching Pokémons
    description: Base methods to fetch Pokemon information.
