# To fetch schema from
#introspection: file://IntrospectionQuery.txt
introspection: file://GraphQLSchema.graphql

# Specify information about your server
servers:
  - url: http://localhost:8000/gql
    description: Your GraphQL Server

# General information about your API documentation
info:
  description: |
    Documentation for your GraphQL API
  version: 1.0.0
  title: API Documentation

# Define domains and their descriptions (you can customize this based on your schema structure)
domains:
  - name: Finance
    description: Methods related to finance
  - name: Project
    description: Methods related to projects
  - name: Milestone
    description: Methods related to milestones
  - name: StatementOfWork
    description: Methods related to statements of work

# Additional configuration options if needed
